// The 2026-09-03 owner report, turned into a standing measurement.
//
// REPORT: saying 「还有一个小问题，就是这个问题要怎么处理呢」 in translate mode on
// the light-record page showed 「AI 生成内容未通过校验」 (COMPOSE_OUTPUT_REJECTED),
// on iOS and on Android. The obvious reading — "the guard is rejecting normal
// content" — is the one this file exists to refute WITH NUMBERS rather than with
// an argument, because the argument is cheap and this repo has been wrong about
// it before.
//
// 🔴 WHAT WAS ACTUALLY HAPPENING (production, JP relay server.log, five WARN
// lines 2026-09-03 03:34:45 → 03:37:08): every rejection is
// `rule: target_script_absent`, `target_lang: 'en'`, `output_chars: 18|20`. The
// model returned ~20 characters with no Latin in them — it had not translated.
// Cause and fix live in `compose/prompt.ts`; see
// `compose-translate-output-language.test.ts`.
//
// 🔴 WHAT THIS FILE PINS: the guard does not reject a CORRECT translation of the
// reported sentence, or of 64 more ordinary dictated ones. Every "faithful
// output" below is HAND-WRITTEN — no model produced any of them. That is not
// fastidiousness: an output generated by the same class of model the guard
// judges would make this suite measure the model's habits instead of the guard's
// thresholds, and a green would then mean nothing about a different model.
//
// ⚠️ AND THE OTHER HALF, which is the half that decays: the reverse controls at
// the bottom must STAY rejected. A file that only asserts acceptance is one
// commit away from being satisfied by deleting the guard.

import { describe, expect, it } from 'vitest';
import { guardComposeOutput, type ComposeGuardTask } from '../src/compose/output-guard';

type Case = readonly [string, ComposeGuardTask, string, string | undefined, string, string];

const OWNER_SENTENCE = '还有一个小问题，就是这个问题要怎么处理呢';

/** Ordinary things a dictation user says, with a faithful hand-written output. */
const ACCEPT: readonly Case[] = [
  // ── the reported sentence, in the renderings a competent translator gives ──
  ['owner-01', 'translate', 'zh', 'en', OWNER_SENTENCE, 'There is one more small question: how should this problem be handled?'],
  ['owner-02', 'translate', 'zh', 'en', OWNER_SENTENCE, 'One more small issue: how do we deal with this problem?'],
  ['owner-03', 'translate', 'zh', 'en', OWNER_SENTENCE, "There's another small question — how should we handle this?"],
  ['owner-04', 'translate', 'zh', 'en', OWNER_SENTENCE, 'There is one more small question, and that is how this particular problem ought to be handled.'],
  // ── questions: the family owner's sentence belongs to, and the family a
  //    model is most likely to ANSWER instead of translate. A guard that could
  //    not tell the two apart would show up right here.
  ['q-01', 'translate', 'zh', 'en', '这个问题怎么办', 'What should we do about this problem?'],
  ['q-02', 'translate', 'zh', 'en', '那这个问题应该怎么解决才好呢？', 'So how should this problem best be solved?'],
  ['q-03', 'translate', 'zh', 'en', '你觉得这样处理有没有问题？', 'Do you think there is any problem with handling it this way?'],
  ['q-04', 'translate', 'zh', 'en', '这个功能什么时候能上线', 'When will this feature go live?'],
  ['q-05', 'translate', 'zh', 'en', '会议改到几点了', 'What time was the meeting moved to?'],
  ['q-06', 'translate', 'zh', 'en', '我们要不要先问一下客户的意见呢', 'Should we ask the customer what they think first?'],
  ['q-07', 'translate', 'zh', 'en', '这个问题是不是之前也出现过一次', 'Did this problem come up once before as well?'],
  ['q-08', 'translate', 'zh', 'en', '怎么办', 'What should we do?'],
  ['q-09', 'translate', 'zh', 'en', '为什么', 'Why?'],
  // ── statements, including the short ones where a ratio gate is noise ──
  ['s-01', 'translate', 'zh', 'en', '这个方案我觉得还可以，就是时间有点紧', 'I think this plan is fine, the schedule is just a bit tight.'],
  ['s-02', 'translate', 'zh', 'en', '明天下午三点开会，记得带上材料', 'The meeting is tomorrow at three in the afternoon; remember to bring the materials.'],
  ['s-03', 'translate', 'zh', 'en', '我先把这一版发给你看看', 'Let me send you this version first so you can take a look.'],
  ['s-04', 'translate', 'zh', 'en', '昨天那个问题已经修好了', 'That problem from yesterday has already been fixed.'],
  ['s-05', 'translate', 'zh', 'en', '没关系', 'It does not matter.'],
  ['s-06', 'translate', 'zh', 'en', '辛苦了', 'Thank you for your hard work.'],
  ['s-07', 'translate', 'zh', 'en', '好的，我知道了', 'All right, I understand.'],
  ['s-08', 'translate', 'zh', 'en', '这段话麻烦你再确认一下，我担心有歧义', 'Please double-check this passage; I am worried it is ambiguous.'],
  ['s-09', 'translate', 'zh', 'en', '我们把这个问题拆成三个小问题来看', 'Let us break this problem into three smaller ones.'],
  ['s-10', 'translate', 'zh', 'en', '我今天有点不舒服，可能要晚一点到', 'I am not feeling well today, so I may arrive a little late.'],
  ['s-11', 'translate', 'zh', 'en', '这个报告我看完了，整体没什么大问题', 'I have read the report; on the whole there is nothing seriously wrong with it.'],
  ['s-12', 'translate', 'zh', 'en', '请把门轻轻关上', 'Please close the door gently.'],
  ['s-13', 'translate', 'zh', 'en', '把音量调到最大', 'Turn the volume all the way up.'],
  // 成语 (chengyu) — four characters carrying a whole proposition. These are the
  // shape that broke the volume budget once (2026-08-08) and they stay here as
  // the standing check that the dense-short allowance still holds.
  ['s-14', 'translate', 'zh', 'en', '画蛇添足', 'To ruin something by adding what is unnecessary.'],
  ['s-15', 'translate', 'zh', 'en', '亡羊补牢', 'To mend the fold after the sheep are lost.'],
  // ── numbers, dates, URLs, Latin tokens inside Chinese speech ──
  ['n-01', 'translate', 'zh', 'en', '这次一共有三个问题需要处理', 'There are three problems to deal with this time.'],
  ['n-02', 'translate', 'zh', 'en', '预算是二十五万，比上次多了一点', 'The budget is 250,000, a little more than last time.'],
  ['n-03', 'translate', 'zh', 'en', '文档在 https://example.com/docs 上面', 'The document is at https://example.com/docs .'],
  ['n-04', 'translate', 'zh', 'en', '请在 2026 年 9 月 3 日之前提交', 'Please submit before 3 September 2026.'],
  ['n-05', 'translate', 'zh', 'en', '这个接口返回 200 就算成功', 'If this endpoint returns 200 it counts as a success.'],
  ['n-06', 'translate', 'zh', 'en', '把 Docker 镜像重新打一下', 'Please rebuild the Docker image.'],
  ['n-07', 'translate', 'zh', 'en', 'GitHub 上那个 issue 还没关', 'That issue on GitHub is still open.'],
  ['n-08', 'translate', 'zh', 'en', '用 FlowMic 说一句话试试', 'Try saying one sentence with FlowMic.'],
  // 十分 / 万一 are ordinary words spelled with numeral characters.
  ['n-09', 'translate', 'zh', 'en', '十分感谢你的帮助', 'Thank you very much for your help.'],
  ['n-10', 'translate', 'zh', 'en', '万一他不同意怎么办', 'What if he does not agree?'],
  // ── the other targets the picker offers ──
  ['t-de', 'translate', 'zh', 'de', '这个问题要怎么处理呢', 'Wie soll dieses Problem behandelt werden?'],
  ['t-fr', 'translate', 'zh', 'fr', '明天上午我们再讨论一次', 'Nous en discuterons encore demain matin.'],
  ['t-es', 'translate', 'zh', 'es', '这个方案还需要再改一版', 'Este plan todavia necesita otra revision.'],
  ['t-ru', 'translate', 'zh', 'ru', '会议推迟到下周', 'Встреча перенесена на следующую неделю.'],
  ['t-ja', 'translate', 'zh', 'ja', '这个问题要怎么处理呢', 'この問題はどう対処すればよいでしょうか。'],
  ['t-ko', 'translate', 'zh', 'ko', '明天见', '내일 봐요.'],
  ['t-tw', 'translate', 'zh', 'zh-TW', '这个问题要怎么处理呢', '這個問題要怎麼處理呢'],
  // ── the other direction, and the proper-noun passthroughs ──
  ['r-01', 'translate', 'en', 'zh', 'How should we handle this issue?', '我们该怎么处理这个问题？'],
  ['r-02', 'translate', 'en', 'zh', 'There is one more small question.', '还有一个小问题。'],
  ['r-03', 'translate', 'en', 'zh', 'Can you send me the file before five?', '你能在五点前把文件发给我吗？'],
  ['r-04', 'translate', 'en', 'zh', 'OK', '好的'],
  ['r-05', 'translate', 'en', 'zh', 'New York Times', '纽约时报'],
  ['r-06', 'translate', 'en', 'zh', 'FlowMic', 'FlowMic'],
  ['r-07', 'translate', 'en', 'zh', 'The build failed with exit code 1.', '构建失败，退出码为 1。'],
  ['r-08', 'translate', 'en', 'de', 'Windows Update', 'Windows Update'],
  ['r-09', 'translate', 'en', 'ja', 'Please close the window.', '窓を閉めてください。'],
  ['r-10', 'translate', 'ja', 'en', 'この問題はどう対処すればいいですか', 'How should this problem be dealt with?'],
  ['r-11', 'translate', 'ja', 'en', '明日の午後三時に会議があります', 'There is a meeting tomorrow at three in the afternoon.'],
  ['r-12', 'translate', 'ja', 'en', 'すみません、少し遅れます', 'Sorry, I will be a little late.'],
  // ── code-mixed speech, which is what this product's users actually dictate ──
  ['m-01', 'translate', 'zh', 'en', '这个 API 的文档要怎么找', 'How do I find the documentation for this API?'],
  ['m-02', 'translate', 'zh', 'en', '把 Slack 通知关掉', 'Turn off the Slack notifications.'],
  ['m-03', 'translate', 'zh', 'en', '我们用 TypeScript 重写了这一部分', 'We rewrote this part in TypeScript.'],
  // ── organize / draft_polish: the same question on the other two tasks ──
  ['o-01', 'organize', 'zh', undefined, '嗯就是那个，我们明天，明天下午三点开会啊，然后记得带材料', '我们明天下午三点开会，记得带材料。'],
  ['o-02', 'organize', 'zh', undefined, '这个问题呢，就是说，我觉得吧，还是要先问一下客户的意见比较好', '这个问题我觉得还是要先问一下客户的意见比较好。'],
  ['o-03', 'organize', 'zh', undefined, '一共有三个问题，第一个是性能，第二个是文档，第三个嗯就是测试覆盖', '一共有 3 个问题：1 性能，2 文档，3 测试覆盖。'],
  ['o-04', 'organize', 'zh', undefined, '那个 Docker 镜像啊，就是，重新打一下就好了', '那个 Docker 镜像重新打一下就好了。'],
  ['o-05', 'organize', 'en', undefined, 'so um the the meeting is uh tomorrow at three and please bring the the materials', 'The meeting is tomorrow at three; please bring the materials.'],
  ['o-06', 'organize', 'zh', undefined, '我们把这个问题拆成三个小问题来看，第一个是接口设计，第二个是数据结构，第三个是错误处理，这样比较清楚一点', '我们把这个问题拆成三个小问题：第一是接口设计，第二是数据结构，第三是错误处理，这样更清楚。'],
  ['p-01', 'draft_polish', 'zh', undefined, '这个问题我觉得还是要在再确认一下比较好', '这个问题我觉得还是要再确认一下比较好。'],
  ['p-02', 'draft_polish', 'en', undefined, 'i think we should to check this issue one more time', 'I think we should check this issue one more time.'],
];

const verdict = (c: Case) => {
  const [, task, sl, tl, source, output] = c;
  return guardComposeOutput({
    task,
    source,
    output,
    ...(sl !== undefined ? { source_lang: sl } : {}),
    ...(tl !== undefined ? { target_lang: tl } : {}),
  });
};

describe('compose guard — ordinary dictated speech is not rejected', () => {
  it.each(ACCEPT.map((c) => [c[0], c] as const))('accepts %s', (_id, c) => {
    const v = verdict(c as Case);
    expect(v.ok ? null : `${v.rule}: ${v.detail}`).toBeNull();
  });

  it('rejects none of the whole set — the number, not just the individual greens', () => {
    // Stated as a count on purpose. The per-case assertions above go red one at a
    // time and are easy to delete; this one says what the false-reject rate IS,
    // and any future loosening/tightening has to move it deliberately.
    const rejected = ACCEPT.filter((c) => !verdict(c).ok).map((c) => c[0]);
    expect(rejected).toEqual([]);
    expect(ACCEPT.length).toBeGreaterThanOrEqual(60);
  });
});

describe('compose guard — the reverse controls it exists for still fire', () => {
  // 🔴 Read this next to the block above, never on its own. The point of the
  // acceptance set is that the guard is not trigger-happy; the point of THIS set
  // is that it is still a guard. owner's FB-5 line — "the model is here to
  // translate the sentence, not to answer it" — lives in these five rows.
  it('an answer instead of a translation', () => {
    const v = guardComposeOutput({
      task: 'translate', source_lang: 'zh', target_lang: 'en', source: OWNER_SENTENCE,
      output: "Sure! Here's how you can handle that problem: first, identify the root cause, then apply a fix and verify it.",
    });
    expect(v.ok ? 'ACCEPTED' : v.rule).toBe('assistant_frame');
  });

  it('the source handed back untranslated — the exact production failure of 2026-09-03', () => {
    // This is what the model really returned in owner's five turns. If this row
    // ever goes green, the user is being shown their own Chinese as a translation
    // and nothing anywhere says so.
    const v = guardComposeOutput({
      task: 'translate', source_lang: 'zh', target_lang: 'en', source: OWNER_SENTENCE, output: OWNER_SENTENCE,
    });
    expect(v.ok ? 'ACCEPTED' : v.rule).toBe('target_script_absent');
  });

  it('a lightly reworded Chinese echo — what production actually logged at 20 chars', () => {
    const v = guardComposeOutput({
      task: 'translate', source_lang: 'zh', target_lang: 'en',
      source: OWNER_SENTENCE, output: '还有一个问题，就是这个问题要怎么处理呢？',
    });
    expect(v.ok ? 'ACCEPTED' : v.rule).toBe('target_script_absent');
  });

  it('the model acting on a dictated imperative', () => {
    const v = guardComposeOutput({
      task: 'translate', source_lang: 'zh', target_lang: 'en',
      source: '把音量调到最大', output: 'Volume set to 100%. Be careful, it might be loud!',
    });
    expect(v.ok ? 'ACCEPTED' : v.rule).toBe('volume_runaway');
  });

  it('organize inventing a fact that was never said', () => {
    const v = guardComposeOutput({
      task: 'organize', source_lang: 'zh',
      source: '我们讨论了一下这个方案的细节，大家都觉得可以推进，下周开始',
      output: '我们讨论了方案细节，一致同意推进，下周一开始，预计 30 天完成。',
    });
    expect(v.ok ? 'ACCEPTED' : v.rule).toBe('invented_numerals');
  });
});
