// Owner-authored locale leaves; this adapter maps closed UI states to keys.
import '../settings/app_strings.dart';
import 'mcp_channel.dart';
import 'mcp_transport.dart';

enum McpText {
  title,
  scope,
  enableDisclosure,
  noRemoteDelete,
  endpoint,
  credential,
  authNone,
  authBearer,
  oauthUnsupported,
  httpsRequired,
  protocolUnsupported,
  noTools,
  chooseTool,
  chooseToolHint,
  mapping,
  mappingInvalid,
  secretValue,
  test,
  testPassed,
  testFailed,
  lastCallSuccess,
  unconfigured,
  saved,
  enabled,
  paused,
  reauthorize,
  toolMissing,
  schemaUnsupported,
  storageUnavailable,
  pending,
  sending,
  toolResult,
  rejected,
  unknown,
  retrying,
  remoteRejected,
  retryExhausted,
  expired,
  contentNotReady,
  localChanged,
  manualDisclosure,
  unknownRetryWarning,
  restoreNeedsCredential,
  enable,
  pause,
  retry,
  manual,
  sourceFixed,
  sourceText,
  outputText,
  processedText,
  sourceLang,
  outputLang,
  processMode,
  entryType,
  articleId,
  entryId,
  createdIso,
  createdMs,
  createdSeconds,
  recordJson,
  deleteDisclosure,
  previousConfiguration,
  discardInvalid
}

extension McpCopy on AppStrings {
  String mcp(McpText key, {String host = '', String tool = '', String field = '', int count = 0}) => switch (key) {
    McpText.title => recordSubmitTitle,
    McpText.scope => recordSubmitScope,
    McpText.enableDisclosure => recordSubmitEnableDisclosure(tool, host),
    McpText.noRemoteDelete => recordSubmitNoRemoteDelete,
    McpText.endpoint => recordSubmitEndpoint,
    McpText.credential => recordSubmitCredential,
    McpText.authNone => recordSubmitAuthNone,
    McpText.authBearer => recordSubmitAuthBearer,
    McpText.oauthUnsupported => recordSubmitOAuthUnsupported,
    McpText.httpsRequired => recordSubmitHttpsRequired,
    McpText.protocolUnsupported => recordSubmitProtocolUnsupported,
    McpText.noTools => recordSubmitNoTools,
    McpText.chooseTool => recordSubmitChooseTool,
    McpText.chooseToolHint => recordSubmitChooseToolHint,
    McpText.mapping => recordSubmitMapping,
    McpText.mappingInvalid => recordSubmitMappingInvalid(field),
    McpText.secretValue => recordSubmitSecretValue,
    McpText.test => recordSubmitTest,
    McpText.testPassed => recordSubmitTestPassed,
    McpText.testFailed => recordSubmitTestFailed,
    McpText.lastCallSuccess => recordSubmitLastCallSuccess,
    McpText.unconfigured => recordSubmitUnconfigured,
    McpText.saved => recordSubmitSaved,
    McpText.enabled => recordSubmitEnabled,
    McpText.paused => recordSubmitPaused,
    McpText.reauthorize => recordSubmitReauthorize,
    McpText.toolMissing => recordSubmitToolMissing,
    McpText.schemaUnsupported => recordSubmitSchemaUnsupported,
    McpText.storageUnavailable => recordSubmitStorageUnavailable,
    McpText.pending => recordSubmitPending,
    McpText.sending => recordSubmitSending,
    McpText.toolResult => recordSubmitToolResult,
    McpText.rejected => recordSubmitRejected,
    McpText.unknown => recordSubmitUnknown,
    McpText.retrying => recordSubmitRetrying,
    McpText.remoteRejected => recordSubmitRemoteRejected,
    McpText.retryExhausted => recordSubmitRetryExhausted,
    McpText.expired => recordSubmitExpired(count),
    McpText.contentNotReady => recordSubmitContentNotReady,
    McpText.localChanged => recordSubmitLocalChanged,
    McpText.manualDisclosure => recordSubmitManualDisclosure,
    McpText.unknownRetryWarning => recordSubmitUnknownRetryWarning,
    McpText.restoreNeedsCredential => recordSubmitRestoreNeedsCredential,
    McpText.enable => recordSubmitEnable,
    McpText.pause => recordSubmitPause,
    McpText.retry => recordSubmitRetry,
    McpText.manual => recordSubmitManual,
    McpText.sourceFixed => recordSubmitSourceFixed,
    McpText.sourceText => recordSubmitSourceText,
    McpText.outputText => recordSubmitOutputText,
    McpText.processedText => recordSubmitProcessedText,
    McpText.sourceLang => recordSubmitSourceLang,
    McpText.outputLang => recordSubmitOutputLang,
    McpText.processMode => recordSubmitProcessMode,
    McpText.entryType => recordSubmitEntryType,
    McpText.articleId => recordSubmitArticleId,
    McpText.entryId => recordSubmitEntryId,
    McpText.createdIso => recordSubmitCreatedIso,
    McpText.createdMs => recordSubmitCreatedMs,
    McpText.createdSeconds => recordSubmitCreatedSeconds,
    McpText.recordJson => recordSubmitRecordJson,
    McpText.deleteDisclosure => recordSubmitDeleteDisclosure,
    McpText.previousConfiguration => recordSubmitPreviousConfiguration,
    McpText.discardInvalid => recordSubmitDiscardInvalid,
  };
}

McpText channelText(McpChannelState state) => switch (state) {
  McpChannelState.saved => McpText.saved, McpChannelState.enabled => McpText.enabled,
  McpChannelState.paused => McpText.paused, McpChannelState.reauthorizationRequired => McpText.reauthorize,
  McpChannelState.toolMissing => McpText.toolMissing, McpChannelState.schemaUnsupported => McpText.schemaUnsupported,
  McpChannelState.storageUnavailable => McpText.storageUnavailable,
};
McpText replyText(McpReply reply) {
  if (reply.oauthChallenge) return McpText.oauthUnsupported;
  if (reply.status == 401) return McpText.reauthorize;
  if (reply.code == -32022) return McpText.protocolUnsupported;
  return switch (reply.reason) {
    'test_passed' => McpText.testPassed, 'https_required' => McpText.httpsRequired,
    'protocol_unsupported' => McpText.protocolUnsupported, 'schema_unsupported' => McpText.schemaUnsupported,
    'tool_missing' => McpText.toolMissing, 'local_mapping' => McpText.mappingInvalid,
    'credential_unavailable' => McpText.restoreNeedsCredential, 'storage_unavailable' => McpText.storageUnavailable,
    'reauthorization_required' => McpText.reauthorize, _ => McpText.testFailed,
  };
}
