// V2-07.8a UI string catalogue — now with the locale axis the old header
// promised as「a later 偏好 card」("a later preference card"). This IS that card.
//
// Red-line clarification (docs/decisions/2026-07-28-i18n-four-locales-and-theme.md):
// 「UI 不跟随 OS locale」("UI does not follow OS locale") has not been
// overturned — what it forbids is「从系统 locale 推断」("inferring from the
// system locale"), not multiple languages. The UI language recognizes only
// two things: the user's explicit choice (setLocale), or the choice
// persisted in storage (hydrateLocale). Both live in ./strings/locale.ts;
// this file never touches the OS.
//
// Mechanism (why not one of the hundreds of `S.foo` call sites needs to change):
//   ① Each shard went from 「a single zh constant」to 「a per-locale table
//      per key」({ 'zh-CN': {...}, en: {...}, ja: {...}, ko: {...} } as
//      const — four locales as of V2-07.8b; Record<UiLocale, …>
//      compile-time-forces every shard to hand over all four);
//   ② This file merges the ten shards by locale into S_BY_LOCALE, then turns
//      S into a **reactive object**, initialized to the current locale's copy;
//   ③ setLocale() changes the ref in locale.ts → the onLocaleChange
//      subscription here does Object.assign(S, S_BY_LOCALE[new locale]) to
//      swap the whole value in place;
//   ④ `S.foo` in templates reads a reactive property at render time; Vue's
//      dependency tracking makes every component that uses it re-render on
//      its own — no restart, no refresh, call sites untouched.
//   The derived tables (MODE_BADGE / TL_BATCH_MSG / SIDECAR_LABEL /
//   INJECT_FAIL_REASON) work the same way: they stay in their original
//   shard, read getLocale() (a ref) via a getter/function, and get tracked
//   the moment they're called during render. Circular imports are avoided by
//   the one-directional edge "shard → locale.ts leaf" (the circular-import
//   lint runs Tarjan across the whole repo — no cycles).
//
// 🔴 Correction (2026-08-14, nine-locale migration) — of the ① above, only
// half is still true; the original text is kept because ②③④ haven't changed
// a single character, and those three are what makes "call sites don't need
// to change" hold.
//   · Shards **no longer hold a per-locale table**: each now declares
//     **which keys this shard has** (`export const NAV_KEYS = [...]`, with
//     each key's rationale comment still sitting next to it); the
//     translations live in `i18n/desktop/<code>.json`, and the merged table
//     is generated by `scripts/i18n/gen-desktop-ts.mjs` into
//     `./strings/generated/catalogue.g.ts`.
//   · The guard "`Record<UiLocale, …>` compile-time-forces every shard to
//     hand over all four" **is gone**; what replaced it is owner's
//     2026-08-14 ruling to fall missing translations back to English (book
//     17, §0-bis): the generator emits each language as
//     `{ ...EN, …whatever it has translated… }` ⇒ a missing translation is
//     structurally guaranteed to be English, never an empty string or a bare
//     key; **the cost is that we now have to know for ourselves how much is
//     missing** ⇒ `i18n/desktop/coverage.json` is how that half gets paid
//     off, and `i18n-generated-fresh` is its gate.
//   · Adding a tenth language now **touches neither this file nor any single
//     shard**: add a line to the registry + a data file + run the generator
//     once (docs/strategy/2026-08-14-locale-expansion-architecture.md §2).
//
// Guard: S_BY_LOCALE is the guard/test surface — locale-parity.test.ts
// asserts that every locale's key set exactly matches the baseline locale's,
// printing any missing keys by name.
// Note ./strings/ deliberately has no index.ts — with moduleResolution:Bundler
// a bare './strings' always resolves to THIS file.

import { reactive } from 'vue';
import { NAV_STRINGS } from './strings/nav';
import { DEVICES_STRINGS } from './strings/devices';
import { CLOUD_STRINGS } from './strings/cloud';
import { PAIRING_STRINGS } from './strings/pairing';
import { SETTINGS_STRINGS } from './strings/settings';
import { TIMELINE_STRINGS } from './strings/timeline';
import { SEARCH_STRINGS } from './strings/search';
import { CAPSULE_STRINGS } from './strings/capsule';
import { CONNECTION_STRINGS } from './strings/connection';
import { SIDECAR_STRINGS } from './strings/sidecar';
import { PROBE_STRINGS } from './strings/probe';
// Data (export / import, docs/rebuild/16 FPR v1).
import { PORTABLE_STRINGS } from './strings/portable';
// Stats + clear (window C2, docs/rebuild/16 §6.1 / §6.2).
import { STATS_STRINGS } from './strings/stats';
// 0.3.0 P1 — 「你说的话去了哪里」("where did what you said go"): the core audio → recognition → optional LLM →
// injection path. Legal texts are website links (owner 2026-08-14); the steps
// stay because they answer this machine's configuration.
import { DISCLOSURE_STRINGS } from './strings/disclosure';
// UP-3b in-app update (design doc §5.2). Failure copy corresponds 1:1 with
// Rust's UpdateFailure::tag(); update-tag-parity.test.ts reads failure.rs as
// data to guard it.
import { UPDATE_STRINGS } from './strings/update';
import type { StringKey } from './strings/generated/catalogue.g';
import { getLocale, onLocaleChange, UI_LOCALES, type UiLocale } from './strings/locale';

// 🔴 THE FIFTEEN SHARDS, LISTED ONCE — and the reason it is a list and not a
// generated table. Each shard's `*_STRINGS` is a VIEW of the generated
// catalogue sliced by that shard's own key contract, so this array is what
// keeps every shard file wired into production: a shard that stops being
// listed here stops contributing keys to `S`, and the parity/coverage numbers
// say so immediately. Written as data rather than as fifteen spreads per
// locale because the per-locale dimension is exactly what this migration
// removed — the old form was 15 × 4 spread lines and would have been 15 × 9.
const SHARD_VIEWS = [
  NAV_STRINGS,
  DEVICES_STRINGS,
  CLOUD_STRINGS,
  PAIRING_STRINGS,
  SETTINGS_STRINGS,
  TIMELINE_STRINGS,
  SEARCH_STRINGS,
  CAPSULE_STRINGS,
  CONNECTION_STRINGS,
  SIDECAR_STRINGS,
  PROBE_STRINGS,
  PORTABLE_STRINGS,
  STATS_STRINGS,
  DISCLOSURE_STRINGS,
  UPDATE_STRINGS,
] as const;

export type { StringKey };

/** Guard/test surface: the full per-locale merged catalogues. */
export const S_BY_LOCALE = Object.fromEntries(
  UI_LOCALES.map((l) => [
    l,
    Object.assign({}, ...SHARD_VIEWS.map((shard) => shard[l])) as Record<StringKey, string>,
  ]),
) as Record<UiLocale, Record<StringKey, string>>;

export const S: Record<StringKey, string> = reactive({ ...S_BY_LOCALE[getLocale()] });

onLocaleChange((l) => {
  Object.assign(S, S_BY_LOCALE[l]);
  // <html lang> follows the EXPLICIT choice only (affects font/IME heuristics);
  // it is set again at hydrate — it never comes from the OS either.
  if (typeof document !== 'undefined') document.documentElement.lang = l;
});

export { SIDECAR_LABEL } from './strings/sidecar';
export { INJECT_FAIL_REASON } from './strings/capsule';
export { MODE_BADGE } from './strings/timeline';
export {
  UI_LOCALES,
  DEFAULT_LOCALE,
  BASE_LOCALE,
  LOCALE_ENDONYM,
  LOCALE_KEY,
  getLocale,
  setLocale,
  hydrateLocale,
  isUiLocale,
  onLocaleChange,
  wireLocaleStore,
  type UiLocale,
} from './strings/locale';
