// Tests for `extract.rs`.
//
// ── WHAT THESE PROVE, AND WHAT THEY DO NOT ──────────────────────────────────
//
// The fixtures are zips this file builds by hand, so DEFLATE members are
// compressed by `flate2` and decompressed by `flate2`. That is a round trip
// inside one library, and it is worth naming as the limit it is: it proves the
// wiring (raw DEFLATE, not zlib-wrapped; the local header's own name/extra
// lengths; the central directory's uncompressed size as the authority), and it
// does NOT prove we can read what bsdtar actually writes.
//
// 🔴 That second claim is proven the only way it can be — against the real
// artifact, on a real machine, and it is reported as a measurement rather than
// asserted here: `publish/FlowMic-0.2.59-portable-windows-x64.zip` was extracted
// by this code and compared file-by-file against `publish/FlowMic-portable/`,
// the directory bsdtar packed it FROM. See the card's report. The archive is not
// in version control, so a test that depended on it would be green-when-absent,
// which is worse than a measurement that is honestly located outside the suite.

use super::*;

fn tmp(tag: &str) -> PathBuf {
    let d = std::env::temp_dir().join(format!("fm-update-extract-{}-{tag}", std::process::id()));
    let _ = fs::remove_dir_all(&d);
    fs::create_dir_all(&d).unwrap();
    d
}

/// One member of a fixture archive.
struct Member {
    name: &'static str,
    body: Vec<u8>,
    method: u16,
}

/// Build a zip by hand.
///
/// Hand-rolled rather than produced with a zip crate, for the reason
/// `download_tests.rs` gives about test vectors: a fixture generated by the same
/// machinery under test proves only that it is self-consistent. Here the bytes
/// are laid out from the format specification, so a reader that misreads an
/// offset has nothing agreeing with it.
///
/// ⚠️ CRC-32 fields are left at zero, and neither `portable::zip` nor
/// `extract.rs` reads them. That is a real and deliberate gap: per-entry
/// integrity is covered upstream by the SHA-256 gate over the WHOLE archive
/// (which is strictly stronger — it also covers the central directory), plus the
/// exact decompressed-length check in `copy_exact`. Stated here so the gap is
/// known rather than discovered.
fn build_zip(path: &Path, members: &[Member]) {
    use std::io::Write as _;
    let mut out: Vec<u8> = Vec::new();
    let mut central: Vec<u8> = Vec::new();

    for m in members {
        let payload: Vec<u8> = match m.method {
            0 => m.body.clone(),
            8 => {
                let mut enc = flate2::write::DeflateEncoder::new(Vec::new(), flate2::Compression::default());
                enc.write_all(&m.body).unwrap();
                enc.finish().unwrap()
            }
            // An unsupported method: the payload is irrelevant, the header is the
            // whole test.
            _ => m.body.clone(),
        };
        let local_offset = out.len() as u32;
        out.extend_from_slice(&0x0403_4b50u32.to_le_bytes());
        out.extend_from_slice(&20u16.to_le_bytes()); // version needed
        out.extend_from_slice(&0u16.to_le_bytes()); // flags
        out.extend_from_slice(&m.method.to_le_bytes());
        out.extend_from_slice(&0u16.to_le_bytes()); // time
        out.extend_from_slice(&0u16.to_le_bytes()); // date
        out.extend_from_slice(&0u32.to_le_bytes()); // crc32 — see the note above
        out.extend_from_slice(&(payload.len() as u32).to_le_bytes());
        out.extend_from_slice(&(m.body.len() as u32).to_le_bytes());
        out.extend_from_slice(&(m.name.len() as u16).to_le_bytes());
        // 🔴 A non-empty EXTRA field, on purpose. The local header's extra length
        // routinely differs from the central directory's (bsdtar writes timestamp
        // extras locally), so an extractor that skipped the CENTRAL value would
        // land mid-payload on every real archive and read garbage. Making the two
        // differ here is what turns that into a test rather than a hope.
        let extra: [u8; 4] = [0xAA, 0xBB, 0xCC, 0xDD];
        out.extend_from_slice(&(extra.len() as u16).to_le_bytes());
        out.extend_from_slice(m.name.as_bytes());
        out.extend_from_slice(&extra);
        out.extend_from_slice(&payload);

        central.extend_from_slice(&0x0201_4b50u32.to_le_bytes());
        central.extend_from_slice(&20u16.to_le_bytes()); // version made by
        central.extend_from_slice(&20u16.to_le_bytes()); // version needed
        central.extend_from_slice(&0u16.to_le_bytes()); // flags
        central.extend_from_slice(&m.method.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u32.to_le_bytes());
        central.extend_from_slice(&(payload.len() as u32).to_le_bytes());
        central.extend_from_slice(&(m.body.len() as u32).to_le_bytes());
        central.extend_from_slice(&(m.name.len() as u16).to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes()); // extra len — DIFFERENT from local
        central.extend_from_slice(&0u16.to_le_bytes()); // comment len
        central.extend_from_slice(&0u16.to_le_bytes()); // disk
        central.extend_from_slice(&0u16.to_le_bytes()); // internal attrs
        central.extend_from_slice(&0u32.to_le_bytes()); // external attrs
        central.extend_from_slice(&local_offset.to_le_bytes());
        central.extend_from_slice(m.name.as_bytes());
    }

    let cd_offset = out.len() as u32;
    let cd_size = central.len() as u32;
    out.extend_from_slice(&central);
    out.extend_from_slice(&0x0605_4b50u32.to_le_bytes());
    out.extend_from_slice(&0u16.to_le_bytes());
    out.extend_from_slice(&0u16.to_le_bytes());
    out.extend_from_slice(&(members.len() as u16).to_le_bytes());
    out.extend_from_slice(&(members.len() as u16).to_le_bytes());
    out.extend_from_slice(&cd_size.to_le_bytes());
    out.extend_from_slice(&cd_offset.to_le_bytes());
    out.extend_from_slice(&0u16.to_le_bytes());
    fs::write(path, out).unwrap();
}

fn deflated(name: &'static str, body: Vec<u8>) -> Member {
    Member { name, body, method: 8 }
}
fn stored(name: &'static str, body: Vec<u8>) -> Member {
    Member { name, body, method: 0 }
}

/// 🔴 The headline: a DEFLATE archive extracts, byte for byte.
///
/// This is the capability the whole card rests on and that nothing in this tree
/// had. [measured 2026-08-08] every real file in the shipped portable bundle is
/// method 8, so an extractor that only handled STORE would have failed on the
/// first file on the owner's own machine.
#[test]
fn a_deflate_archive_extracts_byte_for_byte() {
    let dir = tmp("deflate");
    let zip = dir.join("a.zip");
    // Compressible, and larger than one COPY_BUF so the streaming loop runs more
    // than once — a single-read implementation would pass a three-byte fixture.
    let big: Vec<u8> = (0..(COPY_BUF * 3 + 11)).map(|i| (i % 61) as u8).collect();
    build_zip(
        &zip,
        &[
            deflated("FlowMic-portable/FlowMic.exe", big.clone()),
            deflated("FlowMic-portable/resources/server.js", b"console.log(1)".to_vec()),
            stored("FlowMic-portable/resources/package.json", br#"{"type":"module"}"#.to_vec()),
        ],
    );

    let out = dir.join("out");
    let report = extract_into(&zip, &out).expect("a DEFLATE archive must extract");
    assert_eq!(report.files, 3);
    assert_eq!(report.bytes, big.len() as u64 + 14 + 17);

    // The archive's own root is PRESERVED — `swap.rs` renames that inner
    // directory into place, and stripping it here would make this function need
    // to know a root name, which `archive.rs` deliberately made inexpressible.
    let root = out.join("FlowMic-portable");
    assert!(root.is_dir());
    assert_eq!(fs::read(root.join("FlowMic.exe")).unwrap(), big);
    assert_eq!(fs::read(root.join("resources/server.js")).unwrap(), b"console.log(1)");
    assert_eq!(fs::read(root.join("resources/package.json")).unwrap(), br#"{"type":"module"}"#);
}

/// Both methods in one archive — which is exactly what bsdtar produces
/// [measured: {0: 2, 8: 8}, the zeros being directory markers].
#[test]
fn store_and_deflate_members_coexist() {
    let dir = tmp("mixed");
    let zip = dir.join("m.zip");
    build_zip(&zip, &[stored("r/a.txt", b"plain".to_vec()), deflated("r/b.txt", b"squashed".to_vec())]);
    let out = dir.join("out");
    assert_eq!(extract_into(&zip, &out).unwrap().files, 2);
    assert_eq!(fs::read(out.join("r/a.txt")).unwrap(), b"plain");
    assert_eq!(fs::read(out.join("r/b.txt")).unwrap(), b"squashed");
}

/// 🔴 An open set, read honestly: a method we cannot decode is NAMED, never
/// silently skipped and never reported as a generic 「解压失败」("extraction
/// failed").
///
/// The action differs from every other extraction failure — this one says the
/// release chain changed how it packs, i.e. our bug, not the user's disk.
#[test]
fn an_unsupported_compression_method_is_named_not_swallowed() {
    let dir = tmp("bzip");
    let zip = dir.join("z.zip");
    // 12 = BZIP2. Legal zip, and something we cannot read.
    build_zip(&zip, &[Member { name: "r/x.bin", body: b"whatever".to_vec(), method: 12 }]);
    let err = extract_into(&zip, &dir.join("out")).unwrap_err();
    assert_eq!(err.tag(), "archive_compression_unsupported");
    assert!(err.is_blocking(), "we are refusing the package's content — that must be read");
    let msg = err.to_string();
    assert!(msg.contains("12"), "the method must be named: {msg}");
    assert!(msg.contains("r/x.bin"), "the entry must be named: {msg}");
}

/// 🔴 A truncated member is a failure, not a short file.
///
/// The central directory declares a length; if inflating produces fewer bytes,
/// writing what we got and reporting success would put a partial `FlowMic.exe`
/// on disk — and the swap would then replace a working install with it.
#[test]
fn a_member_shorter_than_declared_is_refused() {
    let dir = tmp("short");
    let zip = dir.join("s.zip");
    build_zip(&zip, &[deflated("r/a.bin", b"12345".to_vec())]);
    // Rewrite the central directory's uncompressed size to claim more than the
    // stream holds. The last entry's CD record starts 46 + name bytes before the
    // EOCD; its uncompressed-size field is at +24.
    let mut bytes = fs::read(&zip).unwrap();
    let eocd = bytes.len() - 22;
    let cd_offset = u32::from_le_bytes([bytes[eocd + 16], bytes[eocd + 17], bytes[eocd + 18], bytes[eocd + 19]]) as usize;
    bytes[cd_offset + 24..cd_offset + 28].copy_from_slice(&999u32.to_le_bytes());
    fs::write(&zip, &bytes).unwrap();

    let err = extract_into(&zip, &dir.join("out")).unwrap_err();
    assert_eq!(err.tag(), "extract_failed");
    assert!(err.to_string().contains("short_entry"), "{err}");
    // Transient, so it must NOT demand dismissal — retrying is meaningful.
    assert!(!err.is_blocking());
}

/// A traversal attempt is refused for the WHOLE archive, before a byte is
/// written.
///
/// Half-unpacking a hostile archive and stopping leaves the caller holding a tree
/// it cannot reason about — and `swap.rs` is about to rename such a tree over the
/// user's install.
#[test]
fn an_archive_with_an_unsafe_name_is_refused_whole() {
    let dir = tmp("traversal");
    let zip = dir.join("t.zip");
    build_zip(
        &zip,
        &[deflated("r/ok.txt", b"fine".to_vec()), stored("../escape.txt", b"bad".to_vec())],
    );
    let out = dir.join("out");
    let err = extract_into(&zip, &out).unwrap_err();
    assert_eq!(err.tag(), "archive_unsafe_entry");
    // 🔴 Nothing was written — not even the safe member that came first.
    assert!(!out.join("r/ok.txt").exists(), "a refused archive must leave no files behind");
    assert!(!dir.join("escape.txt").exists());
}

#[test]
fn a_file_that_is_not_a_zip_is_named_as_such() {
    let dir = tmp("notzip");
    let f = dir.join("x.zip");
    fs::write(&f, b"this is not a zip file, it is a sentence").unwrap();
    let err = extract_into(&f, &dir.join("out")).unwrap_err();
    assert_eq!(err.tag(), "archive_unreadable");
    assert!(err.to_string().contains("not_a_zip"));
}

/// `safe_join` refuses by CONSTRUCTION — only `Normal` components survive — so
/// no new spelling of an escape can slip past a string test.
///
/// ⚠️ Path componentisation is platform-owned: on Windows `\` is a separator and
/// `C:\other\x` is Prefix+RootDir (refused); on POSIX `\` is an ordinary
/// character, so the same string is one `Normal` component and is admitted.
/// The security property that must hold on EVERY platform is that a returned
/// path never leaves `base` — not that every Windows-spelled absolute is
/// refused wherever the suite runs.
#[test]
fn safe_join_admits_only_normal_components() {
    let base = Path::new("dest");
    assert!(safe_join(base, "a/b.txt").is_some());
    assert!(safe_join(base, "./a/b.txt").is_some());

    // Escapes that Path recognises on every supported host.
    for bad in ["../x", "a/../../x", "/abs/x", "", "."] {
        assert!(safe_join(base, bad).is_none(), "`{bad}` must not produce a path");
    }

    // Platform-native absolute spelling (uses THIS host's separator).
    let native_abs = format!(
        "{sep}other{sep}x",
        sep = std::path::MAIN_SEPARATOR
    );
    assert!(
        safe_join(base, &native_abs).is_none(),
        "`{native_abs}` is absolute on this host and must be refused"
    );

    // Windows drive-absolute spelling. Expectation follows Path's own reading
    // of the string — never a hard-coded OS name.
    let win_drive = r"C:\other\x";
    match safe_join(base, win_drive) {
        None => {
            assert!(
                Path::new(win_drive).is_absolute(),
                "`{win_drive}` was refused; Path must have seen it as absolute"
            );
        }
        Some(joined) => {
            // POSIX: one Normal component whose bytes contain backslashes.
            // Still under dest — that is the invariant, not "must be None".
            assert!(
                !Path::new(win_drive).is_absolute(),
                "`{win_drive}` produced a path; Path must NOT have seen it as absolute"
            );
            assert!(
                joined.starts_with(base),
                "`{win_drive}` joined to {} which escapes {base:?}",
                joined.display()
            );
            assert_eq!(joined, base.join(win_drive));
        }
    }

    // And the survivors really do stay under the destination.
    let p = safe_join(base, "a/b/c.txt").unwrap();
    assert!(p.starts_with(base));
}
