// Tests for `prefs.rs`.
//
// 🔴 The one that matters is `a_lost_prefs_file_never_invents_a_recent_check`.
// Design §5.0 names「只显示『已是最新』而不显示『上次成功检查于 …』」("showing
// only 'already up to date' without showing 'last successful check at …'") as this
// card's most likely silent failure, and the way that would actually happen is
// not a missing UI element — it is a fallback that manufactures the evidence.

use super::*;

fn tmp(tag: &str) -> std::path::PathBuf {
    let d = std::env::temp_dir().join(format!("fm-update-prefs-{}-{tag}", std::process::id()));
    let _ = std::fs::remove_dir_all(&d);
    std::fs::create_dir_all(&d).unwrap();
    d
}

#[test]
fn the_default_is_checking_on_and_never_having_succeeded() {
    let d = UpdatePrefs::default();
    assert!(d.auto_check, "an update nobody hears about is the same as no update chain");
    assert_eq!(d.last_success_check, None, "「从未成功」 must be the starting truth");
}

#[test]
fn preferences_survive_a_save_and_a_load() {
    let dir = tmp("roundtrip");
    let p = UpdatePrefs {
        auto_check: false,
        last_success_check: Some("2026-08-08T09:12:00Z".to_string()),
        ignored_version: None,
    };
    save_to(&dir, &p).unwrap();
    assert_eq!(load_from(&dir), p);
}

/// 🔴 Losing the file makes us claim LESS knowledge, never more.
///
/// A fallback that invented a timestamp would manufacture the only evidence
/// 「已是最新」("already up to date") has, out of a read error — and it would do so invisibly, because
/// the resulting UI is indistinguishable from a healthy one. That is the exact
/// shape of R11: a status word whose evidence does not support it.
#[test]
fn a_lost_prefs_file_never_invents_a_recent_check() {
    let dir = tmp("lost");
    assert_eq!(load_from(&dir).last_success_check, None);

    for garbage in [&b"{ not json"[..], b"null", b"[]", b"{\"auto_check\":\"yes\"}"] {
        std::fs::write(dir.join("update-prefs.json"), garbage).unwrap();
        let p = load_from(&dir);
        assert_eq!(p.last_success_check, None, "a broken file must not produce a timestamp");
        assert!(p.auto_check, "and it must fall back to the product default");
    }
}

/// A file written by an older build (no `last_success_check` key) still loads,
/// and still says 「从未成功」("never succeeded").
#[test]
fn an_older_file_without_the_timestamp_still_loads() {
    let dir = tmp("older");
    std::fs::write(dir.join("update-prefs.json"), br#"{"auto_check":false}"#).unwrap();
    let p = load_from(&dir);
    assert!(!p.auto_check, "the setting the user chose must survive");
    assert_eq!(p.last_success_check, None);
}

/// 🔴 The timestamp must be a real date, not an approximation that drifts.
///
/// Asserted against KNOWN epoch values rather than against our own output — a
/// vector generated by the code under test proves only that it is deterministic
/// (`download_tests.rs` states the same rule about SHA-256 vectors).
#[test]
fn the_timestamp_matches_known_epoch_values() {
    // 0 → the epoch itself.
    assert_eq!(fmt(0), "1970-01-01T00:00:00Z");
    // 1_000_000_000 → 2001-09-09T01:46:40Z (a widely published value).
    assert_eq!(fmt(1_000_000_000), "2001-09-09T01:46:40Z");
    // A leap day, which a `secs / 365 days` approximation gets wrong:
    // 1_583_020_800 → 2020-03-01T00:00:00Z.
    assert_eq!(fmt(1_583_020_800), "2020-03-01T00:00:00Z");
    // The day before it — the leap day itself.
    assert_eq!(fmt(1_582_934_400), "2020-02-29T00:00:00Z");
    // 2100 is NOT a leap year (divisible by 100, not by 400): 4_107_542_400 is
    // 2100-03-01, so the day before must be 02-28 and not 02-29.
    assert_eq!(fmt(4_107_456_000), "2100-02-28T00:00:00Z");
}

/// Format an arbitrary epoch second the way `now_iso8601` formats "now".
fn fmt(secs: u64) -> String {
    let (y, mo, d, h, mi, s) = civil_from_epoch(secs);
    format!("{y:04}-{mo:02}-{d:02}T{h:02}:{mi:02}:{s:02}Z")
}

/// And the real function produces that same shape — the guard against `fmt` and
/// `now_iso8601` drifting apart, since only the former is exercised above.
#[test]
fn now_has_the_shape_the_vectors_have() {
    let now = now_iso8601();
    assert_eq!(now.len(), 20, "expected YYYY-MM-DDTHH:MM:SSZ, got `{now}`");
    assert!(now.ends_with('Z'));
    assert_eq!(&now[4..5], "-");
    assert_eq!(&now[10..11], "T");
    // A sanity floor: this build cannot have been run before it was written.
    assert!(now.as_str() > "2026-01-01T00:00:00Z", "clock looks wrong: {now}");
}
